version: "2"
volumes:
  blooksMongo:
services:
  dashboard:
    environment:
      - 'MONGO_URL=mongodb://mongo/blooks'
      - 'REDIS_URL=redis://redis'
      - 'ROOT_URL=http://localhost:3000'
    image: 'blooks/dashboard:v0.1.5'
    depends_on:
      - mongo
      - redis
    restart: always
    ports:
      - 3000:3000
  mongo:
    environment:
      - AUTH=no
    image: 'mongo:3'
    restart: always
    ports:
      - 27018:27017
    volumes:
      - blooksMongo:/data/db
  redis:
    image: 'redis:3'
    restart: always
  address-generator:
    image: 'blooks/address-generator:v0.0.8'
    environment:
      - 'MONGO_URL=mongodb://mongo/blooks'
      - 'REDIS_URL=redis://redis'
    depends_on:
      - redis
      - mongo
  address-updater:
    image: 'blooks/address-updater:v0.2.3'
    environment:
      - 'MONGO_URL=mongodb://mongo/blooks'
      - 'REDIS_URL=redis://redis'
    depends_on:
      - mongo
      - redis
  transaction-fetcher:
    image: 'blooks/transaction-fetcher:v0.1.3'
    environment:
      - 'MONGO_URL=mongodb://mongo/blooks'
      - 'REDIS_URL=redis://redis'
    depends_on:
      - mongo
      - redis
  transaction-processor:
    image: 'blooks/transaction-processor:v0.1.4'
    environment:
      - 'MONGO_URL=mongodb://mongo/blooks'
      - 'REDIS_URL=redis://redis'
    depends_on:
      - mongo
      - redis